# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDqiDce6jHDKCKA6D3rVNplWK6YodYcj
"""

import nltk
nltk.download('punkt_tab')
nltk.download('stopwords')
text="They told her that this was her once chance to show the world what she was made of. She believed them at the time. It was the big stage and she knew the world would be there to see. The only one who had disagreed with this sentiment was her brother. He had told her that you dont show the world what you're made of when they are all watching, you show that in your actions when nobody was looking. It was looking more and more like her brother was correct."

sentence=nltk.sent_tokenize(text)

word=nltk.word_tokenize(text)


from nltk.corpus import stopwords
stop_words=stopwords.words('english')


No_word=[]
for w in word:
  if w not in stop_words:
     No_word.append(w)
Summarize_text=" ".join(w for w in No_word)
print(Summarize_text)



